name: Build and Deploy .NET App to AWS EKS via ArgoCD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build & Push Docker Image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check AWS CLI Version
        run: aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 637423294516.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(date +%s)  # Unique timestamp-based tag
          docker build -t 637423294516.dkr.ecr.ap-south-1.amazonaws.com/mywebapp:$IMAGE_TAG -f src/MyWebApp/Dockerfile .
          docker push 637423294516.dkr.ecr.ap-south-1.amazonaws.com/mywebapp:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  update-k8s-manifest:
    name: Update Kubernetes Deployment File
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Deployment YAML with New Image
        run: |
          sed -i "s|637423294516.dkr.ecr.ap-south-1.amazonaws.com/mywebapp:.*|637423294516.dkr.ecr.ap-south-1.amazonaws.com/mywebapp:$IMAGE_TAG|g" k8s-manifests/deployment.yaml
          cat k8s-manifests/deployment.yaml

      - name: Commit & Push Changes
        run: |
          git config --global user.email "divyajyothivundavalli@gmail.com"
          git config --global user.name "DivyaJyothiVundavalli"
          git add k8s-manifests/deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push origin main
